/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.ufms.view;
import br.ufms.bean.Reserva;
import br.ufms.bean.ClienteFisico;
import br.ufms.bean.ClienteJuridico;
import br.ufms.bean.Categorias;
import br.ufms.bean.Automovel;
import br.ufms.bean.ServicosAdicionais;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
/**
 *
 * @author Plabiany
 */
public class CadastroReserva extends javax.swing.JFrame {
   private DefaultComboBoxModel modelCategorias;
   private DefaultComboBoxModel modelServicosAdicionais;
   private DefaultComboBoxModel modelAutomovel;
    /**
     * Creates new form CadastroReserva
     */
    public CadastroReserva() {
        initComponents();
    }
    
    
    public CadastroReserva(Reserva r){
        initComponents();
        
        
        SimpleDateFormat dt = new SimpleDateFormat("dd/MM/yyyy");
        Date d = r.getDataRetirada();
        dataRetirada.setText(dt.format(d));
        
        SimpleDateFormat hr = new SimpleDateFormat("hh:mm");
        Date h = r.getHoraRetirada();
        horaRetirada.setText(hr.format(h));
        
        SimpleDateFormat dtd = new SimpleDateFormat("dd/MM/yyyy");
        Date dev = r.getDataDevolucao();
        dataDev.setText(dtd.format(dev));
        
        SimpleDateFormat hrd = new SimpleDateFormat("hh:mm");
        Date hd = r.getHoraDevolucao();
        horaDev.setText(hrd.format(hd));
        
        if(CPF.isSelected()){
        ClienteFisico c = new ClienteFisico();
        ClienteFisico cpf = c.buscaClienteFisico(idcliente.getText());
        idcliente.setText(cpf.getNome());
        
        }
        
        if (CNPJ.isSelected()){
        ClienteJuridico j = new ClienteJuridico();
        ClienteJuridico juri = j.buscaClienteJuridico(idcliente.getText());
        idcliente.setText(juri.getNome());
        }
        
        
        this.modelCategorias = new DefaultComboBoxModel();
        this.Cat.setModel(this.modelCategorias);
        this.atualizarCategorias();
        
        valorlocacao.setAlignmentY(r.getLocacao());     
        
        this.modelServicosAdicionais = new DefaultComboBoxModel();
        this.jComboBoxServicosAdicionais.setModel(this.modelServicosAdicionais);
        this.atualizarSA();
        
        this.modelAutomovel = new DefaultComboBoxModel();
        this.Automóvel.setModel(this.modelAutomovel);
        this.atualizarAutomovel();
        
        taxaMulta.setAlignmentY(r.getTaxaMulta());
        cartaocliente.setText(r.getCartaoCliente());
        desconto.setAlignmentY(r.getDesconto());
        
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        Save = new javax.swing.JButton();
        Voltar = new javax.swing.JButton();
        dataRetirada = new javax.swing.JTextField();
        dataDev = new javax.swing.JTextField();
        horaRetirada = new javax.swing.JTextField();
        horaDev = new javax.swing.JTextField();
        idcliente = new javax.swing.JTextField();
        valorlocacao = new javax.swing.JTextField();
        taxaMulta = new javax.swing.JTextField();
        cartaocliente = new javax.swing.JTextField();
        desconto = new javax.swing.JTextField();
        CPF = new javax.swing.JRadioButton();
        CNPJ = new javax.swing.JRadioButton();
        jLabel14 = new javax.swing.JLabel();
        Cat = new javax.swing.JComboBox<>();
        jComboBoxServicosAdicionais = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        Automóvel = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setText("RESERVA");

        jLabel2.setText("Horario da Retirada:");

        jLabel3.setText("Data de Retirada:");

        jLabel4.setText("Data de Devolução:");

        jLabel5.setText("Horario de Devolução:");

        jLabel6.setText("Identificação do Cliente:");

        jLabel7.setText("Categoria do Automóvel:");

        jLabel8.setText("Valor da Locação:          R$");

        jLabel9.setText("Serviços Adicionais: ");

        jLabel11.setText("Taxa de Multa (Desistência em menos de 4 horas) :");

        jLabel12.setText("Cartão de Crédito (Cliente):");

        jLabel13.setText("Desconto:");

        Save.setText("Salvar");
        Save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveActionPerformed(evt);
            }
        });

        Voltar.setText("Voltar");
        Voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VoltarActionPerformed(evt);
            }
        });

        horaRetirada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                horaRetiradaActionPerformed(evt);
            }
        });

        horaDev.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                horaDevActionPerformed(evt);
            }
        });

        CPF.setText("Cliente Físico");

        CNPJ.setText("Cliente Jurídico");

        jLabel14.setText("CPF/CNPJ:");

        Cat.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        Cat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CatActionPerformed(evt);
            }
        });

        jComboBoxServicosAdicionais.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel10.setText("Automóvel:");

        Automóvel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(189, 189, 189)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(111, 111, 111)
                        .addComponent(Save)
                        .addGap(89, 89, 89)
                        .addComponent(Voltar)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(desconto))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(CPF)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(CNPJ))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel3)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(dataRetirada, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel4)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(dataDev, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel5))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(horaDev, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(horaRetirada, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(idcliente))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel12)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cartaocliente))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel11)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(taxaMulta, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 5, Short.MAX_VALUE)))
                        .addGap(17, 17, 17))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addGap(18, 18, 18)
                                .addComponent(Automóvel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Cat, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(valorlocacao, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jComboBoxServicosAdicionais, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(dataRetirada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(horaRetirada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(dataDev, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(horaDev, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(CPF)
                    .addComponent(CNPJ))
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idcliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(Automóvel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(Cat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(valorlocacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jComboBoxServicosAdicionais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(taxaMulta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(cartaocliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(desconto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Save)
                    .addComponent(Voltar))
                .addGap(41, 41, 41))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void horaRetiradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_horaRetiradaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_horaRetiradaActionPerformed

    private void horaDevActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_horaDevActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_horaDevActionPerformed

    private void CatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CatActionPerformed

    private void SaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveActionPerformed
            Reserva reserva = new Reserva();
            SimpleDateFormat st = new SimpleDateFormat("dd/MM/yyyy");
            Date dt = new Date();
       try {
           dt = st.parse(this.dataRetirada.getText());
       } catch (ParseException ex) {
           Logger.getLogger(CadastroReserva.class.getName()).log(Level.SEVERE, null, ex);
       }
            reserva.setDataRetirada(dt);
           
            
            
            SimpleDateFormat hr = new SimpleDateFormat("hh:mm");
            Date HR = new Date();
            
       try {
           HR = hr.parse(this.horaRetirada.getText());
       } catch (ParseException ex) {
           Logger.getLogger(CadastroReserva.class.getName()).log(Level.SEVERE, null, ex);
       }
            reserva.setHoraRetirada(HR);
            
            
            
            
            SimpleDateFormat dd = new SimpleDateFormat("dd/MM/yyyy");
            Date datad = new Date();
       try {
           datad = dd.parse(this.dataDev.getText());
       } catch (ParseException ex) {
           Logger.getLogger(CadastroReserva.class.getName()).log(Level.SEVERE, null, ex);
       }
            reserva.setDataDevolucao(datad);
           
            
            SimpleDateFormat horad = new SimpleDateFormat("hh:mm");
            Date hd = new Date();
       try {
           hd = horad.parse(this.horaDev.getText());
       } catch (ParseException ex) {
           Logger.getLogger(CadastroReserva.class.getName()).log(Level.SEVERE, null, ex);
       }
            reserva.setHoraDevolucao(hd);
          
          if(CPF.isSelected()){
              ClienteFisico CF = new ClienteFisico();
              ClienteFisico cf = CF.buscaClienteFisico(idcliente.getText());
              reserva.setCliente(cf);
          }
          
          if(CNPJ.isSelected()){
              ClienteJuridico CJ = new ClienteJuridico();
              ClienteJuridico cj = CJ.buscaClienteJuridico(idcliente.getText());
              reserva.setCliente(cj);
          }
          
          reserva.setLocacao(valorlocacao.getAlignmentX());
          reserva.setTaxaMulta(taxaMulta.getAlignmentX());
          reserva.setCartaoCliente(cartaocliente.getText());
          reserva.setDesconto(desconto.getAlignmentX());
            
    }//GEN-LAST:event_SaveActionPerformed

    private void VoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VoltarActionPerformed
       dispose();
    }//GEN-LAST:event_VoltarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroReserva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroReserva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroReserva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroReserva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroReserva().setVisible(true);
            }
        });
    }
    private void atualizarCategorias() {
        for (Categorias categoria : Categorias.listaCategorias) {
            this.modelCategorias.addElement(categoria.getcodCategoria());
        }
    }
    private void atualizarSA(){
        for(ServicosAdicionais Servicos : ServicosAdicionais.listaServicos){
            this.modelServicosAdicionais.addElement(Servicos.getServico());
        }
    }
    private void atualizarAutomovel(){
        for(Automovel auto : Automovel.getListaAutomovel()){
            this.modelAutomovel.addElement(auto.getModelo());
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> Automóvel;
    private javax.swing.JRadioButton CNPJ;
    private javax.swing.JRadioButton CPF;
    private javax.swing.JComboBox<String> Cat;
    private javax.swing.JButton Save;
    private javax.swing.JButton Voltar;
    private javax.swing.JTextField cartaocliente;
    private javax.swing.JTextField dataDev;
    private javax.swing.JTextField dataRetirada;
    private javax.swing.JTextField desconto;
    private javax.swing.JTextField horaDev;
    private javax.swing.JTextField horaRetirada;
    private javax.swing.JTextField idcliente;
    private javax.swing.JComboBox<String> jComboBoxServicosAdicionais;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField taxaMulta;
    private javax.swing.JTextField valorlocacao;
    // End of variables declaration//GEN-END:variables
}
