/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.ufms.view;

import br.ufms.bean.Automovel;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author leolo
 */
public class MenuAutomovel extends javax.swing.JFrame {

    private static DefaultListModel listModel;
    
    /**
     * Creates new form MenuAutomovel
     */
    public MenuAutomovel() {
        initComponents();
        
        this.listModel = new DefaultListModel();
        this.listAutomovel.setModel(this.listModel);
        MenuAutomovel.atualizarList();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menuTitulo = new java.awt.Label();
        labelTituloAutCadastrados = new java.awt.Label();
        buttonAdicionar = new javax.swing.JButton();
        scrollPaneListAutomovel = new javax.swing.JScrollPane();
        listAutomovel = new javax.swing.JList<>();
        buttonEditar = new javax.swing.JButton();
        buttonExcluir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Menu Automóvel");
        setMinimumSize(new java.awt.Dimension(600, 400));

        menuTitulo.setFont(new java.awt.Font("Dialog", 1, 20)); // NOI18N
        menuTitulo.setText("Menu Automóvel");

        labelTituloAutCadastrados.setText("Automóveis Cadastrados");

        buttonAdicionar.setText("Adicionar");
        buttonAdicionar.setPreferredSize(new java.awt.Dimension(67, 24));
        buttonAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAdicionarActionPerformed(evt);
            }
        });

        listAutomovel.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        scrollPaneListAutomovel.setViewportView(listAutomovel);

        buttonEditar.setText("Editar");
        buttonEditar.setPreferredSize(new java.awt.Dimension(67, 24));
        buttonEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonEditarActionPerformed(evt);
            }
        });

        buttonExcluir.setText("Excluir");
        buttonExcluir.setPreferredSize(new java.awt.Dimension(67, 24));
        buttonExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonExcluirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buttonAdicionar, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(menuTitulo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(63, 63, 63)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(labelTituloAutCadastrados, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(scrollPaneListAutomovel))
                .addContainerGap(51, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(menuTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(labelTituloAutCadastrados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(buttonAdicionar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(buttonEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(buttonExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(scrollPaneListAutomovel))
                .addContainerGap(160, Short.MAX_VALUE))
        );

        menuTitulo.getAccessibleContext().setAccessibleName("Automóvel");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAdicionarActionPerformed
        CadastroAutomovel cadastro = new CadastroAutomovel();
        cadastro.setVisible(true);
    }//GEN-LAST:event_buttonAdicionarActionPerformed

    private void buttonExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonExcluirActionPerformed
        int ind = this.getIndexAutomovel();
        if(ind == -1) return;

        int dialogResult = JOptionPane.showConfirmDialog(this, "Certeza que deseja excluir este Automóvel?", "Warning", JOptionPane.YES_NO_OPTION);
        if(dialogResult == JOptionPane.YES_OPTION) Automovel.removeIndexListaAutomovel(ind);
        MenuAutomovel.atualizarList();
    }//GEN-LAST:event_buttonExcluirActionPerformed

    private void buttonEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonEditarActionPerformed
        int ind = this.getIndexAutomovel();
        if(ind == -1) return;
        
        CadastroAutomovel cadastro = new CadastroAutomovel(Automovel.getAutomovel(ind));
        cadastro.setVisible(true);
    }//GEN-LAST:event_buttonEditarActionPerformed

    private int getIndexAutomovel(){
        int ind = this.listAutomovel.getSelectedIndex();
        if(ind == -1) 
            JOptionPane.showMessageDialog(this, "Selecione um veiculo.", "Error", JOptionPane.ERROR_MESSAGE);
        return ind;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuAutomovel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuAutomovel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuAutomovel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuAutomovel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new MenuAutomovel().setVisible(true);
            }
        });
    }

    public static void atualizarList(){
        MenuAutomovel.listModel.removeAllElements();
        for(Automovel automovel : Automovel.getListaAutomovel()){
            String aux = automovel.getModelo() + " - " + automovel.getPlaca();
            MenuAutomovel.listModel.addElement(aux);
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonAdicionar;
    private javax.swing.JButton buttonEditar;
    private javax.swing.JButton buttonExcluir;
    private java.awt.Label labelTituloAutCadastrados;
    private javax.swing.JList<String> listAutomovel;
    private java.awt.Label menuTitulo;
    private javax.swing.JScrollPane scrollPaneListAutomovel;
    // End of variables declaration//GEN-END:variables
}
